#!/bin/sh
WHITE='\033[1;37m'
RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
DARK_GRAY='\033[1;30m'
PURPLE='\033[0;35m'
NC='\033[0m'
case "$1" in
  "build")
      echo "${YELLOW}Building${NC} backend standalone application ..."
      PWD=$(pwd)
      cd $(echo "$PWD/apps/backend-node-express")
      yarn install
      cd $(echo "$PWD")
      echo "Backend standalone application build finished."
      ;;
  "start")
      PWD=$(pwd)
      cd $(echo "$PWD/apps/backend-node-express")
      yarn start
      cd $(echo "$PWD")
      echo "${LIGHT_GREEN}Starting${NC} backend standalone application ..."
     ;;
  *)
    echo ""
    echo "usage: ./backend COMMAND"
    echo ""
    echo  "Backend standalone application CLI"
    echo ""
    echo "Commands:"
    echo "  build   Install dependencies"
    echo "  start   Start application"
    echo ""
    echo "Examples:"
    echo ""
    echo "  ./backend build"
    echo "  ./backend start"
    echo ""
esac
