#!/bin/sh
RUNNING_ENVIRONMENT="development"
RUNNING_ENVIRONMENT_CMD="dev"
case "$2" in
  "dev")
        RUNNING_ENVIRONMENT="development"
        RUNNING_ENVIRONMENT_CMD="dev"
      ;;
   "prod")
      RUNNING_ENVIRONMENT="production"
      RUNNING_ENVIRONMENT_CMD="prod"
     ;;
   "staging")
      RUNNING_ENVIRONMENT="staging"
      RUNNING_ENVIRONMENT_CMD="staging"
     ;;
    "test")
      RUNNING_ENVIRONMENT="test"
      RUNNING_ENVIRONMENT_CMD="test"
     ;;
esac
ENV_VARS="$(cat environments/${RUNNING_ENVIRONMENT}/.env | xargs)"
export $(echo ${ENV_VARS} | xargs)
case "$1" in
  "build")
      echo "Building application '${COMPOSE_PROJECT_NAME}' blue-green-router, '${RUNNING_ENVIRONMENT}' environment ..."
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && ./scripts 'docker-compose -f docker-compose.blue-green.yml build --quiet' RUNNING_ENVIRONMENT_CMD
      ;;
  "start")
      echo "Starting application '${COMPOSE_PROJECT_NAME}' blue-green-router, '${RUNNING_ENVIRONMENT}' environment ..."
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && ./scripts 'docker-compose -f docker-compose.blue-green.yml up -d' RUNNING_ENVIRONMENT_CMD
     ;;
  "stop")
      echo "Stoping application '${COMPOSE_PROJECT_NAME}' blue-green-router, '${RUNNING_ENVIRONMENT}' environment ..."
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && ./scripts 'docker-compose -f docker-compose.blue-green.yml down' RUNNING_ENVIRONMENT_CMD
     ;;
  "reload-blue")
      echo "Reloading application '${COMPOSE_PROJECT_NAME}' blue-green-router to the 'blue' state, '${RUNNING_ENVIRONMENT}' environment ..."
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && export CURRENT_STATE="blue" && ./scripts 'eval docker exec -it -e BLUE_GREEN_PORT=${BLUE_GREEN_PORT} -e CURRENT_STATE=${CURRENT_STATE} ${COMPOSE_PROJECT_NAME}-router /usr/src/app/reload.sh' RUNNING_ENVIRONMENT_CMD
     ;;
  "reload-green")
      echo "Reloading application '${COMPOSE_PROJECT_NAME}' blue-green-router to the 'green' state, '${RUNNING_ENVIRONMENT}' environment ..."
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && export CURRENT_STATE="green" && ./scripts 'eval docker exec -it -e BLUE_GREEN_PORT=${BLUE_GREEN_PORT} -e CURRENT_STATE=${CURRENT_STATE} ${COMPOSE_PROJECT_NAME}-router /usr/src/app/reload.sh' RUNNING_ENVIRONMENT_CMD
     ;;
  "sh")
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && ./scripts 'eval docker exec -it ${COMPOSE_PROJECT_NAME}-router sh' RUNNING_ENVIRONMENT_CMD
     ;;
  "logs")
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && ./scripts 'eval docker logs ${COMPOSE_PROJECT_NAME}-router' RUNNING_ENVIRONMENT_CMD
     ;;
  "cmd")
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && ./scripts 'eval docker exec -it -e BLUE_GREEN_PORT=${BLUE_GREEN_PORT} -e BLUE_PORT=${BLUE_PORT} -e GREEN_PORT=${GREEN_PORT} -e CURRENT_STATE=${CURRENT_STATE} ${COMPOSE_PROJECT_NAME}-router' RUNNING_ENVIRONMENT_CMD $3 $4 $5 $6 $7 $8 $9
     ;;
  *)
    echo ""
    echo "usage: ./blue-green-router COMMAND [ENVIRONMENT]"
    echo ""
    echo  "Blue/Green mode router for then fullstack application CLI"
    echo ""
    echo "Commands:"
    echo "  build           Build blue/green mode router docker image"
    echo "  start           Start blue/green mode router"
    echo "  stop            Stop blue/green mode router"
    echo "  reload-blue     Reload router config for the blue state"
    echo "  reload-green    Reload router config for the green state"
    echo "  sh              Run shell in router container"
    echo "  logs            Show logs output for the router service"
    echo "  cmd             Run command in the router service container"
    echo ""
    echo "Environments: "
    echo "  dev         Development environment"
    echo "  prod        Production environment"
    echo "  staging     Staging environment"
    echo "  test        Testing environment"
    echo ""
    echo "If omitted, will be used development environment."
    echo ""
    echo "Examples:"
    echo ""
    echo "  ./blue-green-router build"
    echo "  ./blue-green-router start dev"
    echo "  ./blue-green-router stop prod"
    echo "  ./blue-green-router logs dev"
    echo ""
esac