#!/bin/sh
RUNNING_ENVIRONMENT="development"
RUNNING_ENVIRONMENT_CMD="dev"
case "$2" in
  "dev")
        RUNNING_ENVIRONMENT="development"
        RUNNING_ENVIRONMENT_CMD="dev"
      ;;
   "prod")
      RUNNING_ENVIRONMENT="production"
      RUNNING_ENVIRONMENT_CMD="prod"
     ;;
   "staging")
      RUNNING_ENVIRONMENT="staging"
      RUNNING_ENVIRONMENT_CMD="staging"
     ;;
    "test")
      RUNNING_ENVIRONMENT="test"
      RUNNING_ENVIRONMENT_CMD="test"
     ;;
esac
ENV_VARS="$(cat environments/${RUNNING_ENVIRONMENT}/.env | xargs)"
export $(echo ${ENV_VARS} | xargs)
case "$1" in
  "status")
      ./blue-green-router cmd RUNNING_ENVIRONMENT_CMD "wget -q -O - http://127.0.0.1/status | xargs | echo"
      ;;
  "start")
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| starting application  ..."
      ./blue start RUNNING_ENVIRONMENT_CMD
      ./green start RUNNING_ENVIRONMENT_CMD
      ./blue-green-router start RUNNING_ENVIRONMENT_CMD;
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| application started."
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| current state for the application is '$(wget -q -O - http://127.0.0.1/status)'."
      ;;
  "stop")
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| stoping application  ..."
      ./blue stop RUNNING_ENVIRONMENT_CMD
      ./green stop RUNNING_ENVIRONMENT_CMD
      ./blue-green-router stop RUNNING_ENVIRONMENT_CMD;
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| application stopped."
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| current state for the application is '$(wget -q -O - http://127.0.0.1/status)'."
      ;;
  "switch-to-blue")
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| switching application to the 'blue' state ..."
      ./blue build RUNNING_ENVIRONMENT_CMD
      ./blue stop RUNNING_ENVIRONMENT_CMD 
      ./blue start RUNNING_ENVIRONMENT_CMD
      ./blue-green-router cmd RUNNING_ENVIRONMENT_CMD sh -c "\"/etc/nginx/wait-for-http -q -t 60 \\\$(/etc/nginx/get-host|xargs):\${BLUE_PORT}\""
      ./blue-green-router reload-blue RUNNING_ENVIRONMENT_CMD
      ./blue-green-router cmd RUNNING_ENVIRONMENT_CMD sh -c "\"/etc/nginx/wait-for-http -q -t 60 \\\$(/etc/nginx/get-host|xargs):\${BLUE_GREEN_PORT}\"";
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| application switched to the 'blue' state."
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| current state for the application is '$(wget -q -O - http://127.0.0.1/status)'."
     ;;
   "switch-to-green")
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| switching application to the 'green' state ..."
      ./green build RUNNING_ENVIRONMENT_CMD
      ./green stop RUNNING_ENVIRONMENT_CMD 
      ./green start RUNNING_ENVIRONMENT_CMD
      ./blue-green-router cmd RUNNING_ENVIRONMENT_CMD sh -c "\"/etc/nginx/wait-for-http -q -t 60 \\\$(/etc/nginx/get-host|xargs):\${GREEN_PORT}\""
      ./blue-green-router reload-green RUNNING_ENVIRONMENT_CMD
      ./blue-green-router cmd RUNNING_ENVIRONMENT_CMD sh -c "\"/etc/nginx/wait-for-http -q -t 60 \\\$(/etc/nginx/get-host|xargs):\${BLUE_GREEN_PORT}\"";
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| application switched to the 'green' state."
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| current state for the application is '$(wget -q -O - http://127.0.0.1/status)'."
     ;;
  "deploy")
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| deploying application to the new state ..."
      STATE_BEFORE_DEPLOYMENT=$(wget -q -O - http://127.0.0.1/status)
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| current state for the application is '${STATE_BEFORE_DEPLOYMENT}'."
      if [ "$STATE_BEFORE_DEPLOYMENT" == "blue" ];
        then
          ./blue-green switch-to-green RUNNING_ENVIRONMENT_CMD;
        else
          ./blue-green switch-to-blue RUNNING_ENVIRONMENT_CMD;
      fi
     ;;
  "deploy-version")
      DEPLOYMENT_VERSION_TAG=$3
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green:| deploying application ${DEPLOYMENT_VERSION_TAG} version ..."
      git checkout tags/${DEPLOYMENT_VERSION_TAG}
      ./blue-green deploy $2
     ;;
  "rollback")
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| rollback application to the previous state ..."
      STATE_BEFORE_ROLLBACK=$(wget -q -O - http://127.0.0.1/status)
      echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| current state for the application is '${STATE_BEFORE_ROLLBACK}'."
      if [ "$STATE_BEFORE_ROLLBACK" == "blue" ];
        then
          echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| rollback application to the 'green' state ..."
          ./blue-green-router cmd RUNNING_ENVIRONMENT_CMD sh -c "\"/etc/nginx/wait-for-http -q -t 60 \\\$(/etc/nginx/get-host|xargs):\${GREEN_PORT}\"";
          ./blue-green-router reload-green RUNNING_ENVIRONMENT_CMD;
          ./blue-green-router cmd RUNNING_ENVIRONMENT_CMD sh -c "\"/etc/nginx/wait-for-http -q -t 60 \\\$(/etc/nginx/get-host|xargs):\${BLUE_GREEN_PORT}\"";
          echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| current state for the application is '$(wget -q -O - http://127.0.0.1/status)'."
        else
          echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| rollback application to the 'blue' state ..."
          ./blue-green-router cmd RUNNING_ENVIRONMENT_CMD sh -c "\"/etc/nginx/wait-for-http -q -t 60 \\\$(/etc/nginx/get-host|xargs):\${BLUE_PORT}\"";
          ./blue-green-router reload-blue RUNNING_ENVIRONMENT_CMD;
          ./blue-green-router cmd RUNNING_ENVIRONMENT_CMD sh -c "\"/etc/nginx/wait-for-http -q -t 60 \\\$(/etc/nginx/get-host|xargs):\${BLUE_GREEN_PORT}\"";
          echo "|${COMPOSE_PROJECT_NAME}:${RUNNING_ENVIRONMENT}:blue-green| current state for the application is '$(wget -q -O - http://127.0.0.1/status)'."
      fi
     ;;
     
  *)
    echo ""
    echo "usage: ./blue-green COMMAND [ENVIRONMENT] [OPTIONS]"
    echo ""
    echo  "Blue/Green mode for then fullstack application CLI"
    echo ""
    echo "Commands:"
    echo "  status              Show current blue/green mode (environment option is mandatory)"
    echo "  start               Start blue/green mode application"
    echo "  stop                Stop blue/green mode application"
    echo "  switch-to-blue      Build and switch running application to the blue state"
    echo "  switch-to-green     Build and switch running application to the green state"
    echo "  deploy              Build and switch running application to the new state"
    echo "  rolback             Switch running application to the previous state"
    echo "  deploy-version      Build and switch running application to the new state defined by git tag"
    echo ""
    echo "Environments: "
    echo "  dev         Development environment"
    echo "  prod        Production environment"
    echo "  staging     Staging environment"
    echo "  test        Testing environment"
    echo ""
    echo "If omitted, will be used development environment."
    echo ""
    echo "Options: "
    echo ""
    echo "  for the deploy-version command:"
    echo "    [git tag]       Application version defined by git tag"
    echo ""
    echo "Examples:"
    echo ""
    echo "  ./blue-green status dev"
    echo "  ./blue-green start dev"
    echo "  ./blue-green stop prod"
    echo "  ./blue-green switch-to-blue"
    echo "  ./blue-green switch-to-blue"
    echo "  ./blue-green deploy prod"
    echo "  ./blue-green rollback prod"
    echo "  ./blue-green deploy-version prod 0.1.2"
    echo ""
esac