#!/bin/sh
WHITE='\033[1;37m'
RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
DARK_GRAY='\033[1;30m'
PURPLE='\033[0;35m'
NC='\033[0m'
RUNNING_ENVIRONMENT="development"
RUNNING_ENVIRONMENT_CMD="dev"
RUNNING_ENVIRONMENT_LABEL="${DARK_GRAY}${RUNNING_ENVIRONMENT}${NC}"
case "$2" in
  "dev")
        RUNNING_ENVIRONMENT="development"
        RUNNING_ENVIRONMENT_CMD="dev"
        RUNNING_ENVIRONMENT_LABEL="${DARK_GRAY}${RUNNING_ENVIRONMENT}${NC}"
      ;;
   "prod")
      RUNNING_ENVIRONMENT="production"
      RUNNING_ENVIRONMENT_CMD="prod"
      RUNNING_ENVIRONMENT_LABEL="${GREEN}${RUNNING_ENVIRONMENT}${NC}"
     ;;
   "staging")
      RUNNING_ENVIRONMENT="staging"
      RUNNING_ENVIRONMENT_CMD="staging"
      RUNNING_ENVIRONMENT_LABEL="${YELLOW}${RUNNING_ENVIRONMENT}${NC}"
     ;;
    "test")
      RUNNING_ENVIRONMENT="test"
      RUNNING_ENVIRONMENT_CMD="test"
      RUNNING_ENVIRONMENT_LABEL="${PURPLE}${RUNNING_ENVIRONMENT}${NC}"
     ;;
esac
ENV_VARS="$(cat environments/${RUNNING_ENVIRONMENT}/.env | xargs)"
export $(echo ${ENV_VARS} | xargs)
case "$1" in
  "build")
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${BLUE}blue${NC}-${GREEN}green${NC}-router| ${YELLOW}building${NC} application ..."
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && ./scripts 'docker-compose -f docker-compose.blue-green.yml build --quiet' RUNNING_ENVIRONMENT_CMD
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${BLUE}blue${NC}-${GREEN}green${NC}-router| build finished."
     ;;
  "start")
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${BLUE}blue${NC}-${GREEN}green${NC}-router| ${LIGHT_GREEN}starting${NC} application  ..."
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && ./scripts 'docker-compose -f docker-compose.blue-green.yml up -d' RUNNING_ENVIRONMENT_CMD
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${BLUE}blue${NC}-${GREEN}green${NC}-router| application ${GREEN}started${NC}."
     ;;
  "stop")
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${BLUE}blue${NC}-${GREEN}green${NC}-router| ${LIGHT_RED}stoping${NC} application ..."
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && ./scripts 'docker-compose -f docker-compose.blue-green.yml down' RUNNING_ENVIRONMENT_CMD
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${BLUE}blue${NC}-${GREEN}green${NC}-router| application  ${RED}stopped${NC}."
     ;;
  "reload-blue")
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${BLUE}blue${NC}-${GREEN}green${NC}-router| reloading application to the '${BLUE}blue${NC}' state ..."
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && export CURRENT_STATE="blue" && ./scripts 'eval docker exec -it -e BLUE_GREEN_PORT=${BLUE_GREEN_PORT} -e CURRENT_STATE=${CURRENT_STATE} ${COMPOSE_PROJECT_NAME}-router /usr/src/app/reload.sh' RUNNING_ENVIRONMENT_CMD
     ;;
  "reload-green")
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${BLUE}blue${NC}-${GREEN}green${NC}-router| reloading application to the '${GREEN}green${NC}' state ..."
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && export CURRENT_STATE="green" && ./scripts 'eval docker exec -it -e BLUE_GREEN_PORT=${BLUE_GREEN_PORT} -e CURRENT_STATE=${CURRENT_STATE} ${COMPOSE_PROJECT_NAME}-router /usr/src/app/reload.sh' RUNNING_ENVIRONMENT_CMD
     ;;
  "sh")
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && ./scripts 'eval docker exec -it ${COMPOSE_PROJECT_NAME}-router sh' RUNNING_ENVIRONMENT_CMD
     ;;
  "logs")
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && ./scripts 'eval docker logs ${COMPOSE_PROJECT_NAME}-router' RUNNING_ENVIRONMENT_CMD
     ;;
  "cmd")
      export COMPOSE_PROJECT_NAME_PREFIX="blue-green-" && ./scripts 'eval docker exec -it -e BLUE_GREEN_PORT=${BLUE_GREEN_PORT} -e BLUE_PORT=${BLUE_PORT} -e GREEN_PORT=${GREEN_PORT} -e CURRENT_STATE=${CURRENT_STATE} ${COMPOSE_PROJECT_NAME}-router' RUNNING_ENVIRONMENT_CMD $3 $4 $5 $6 $7 $8 $9
     ;;
  *)
    echo ""
    echo "usage: ./blue-green-router COMMAND [ENVIRONMENT]"
    echo ""
    echo  "Blue/Green mode router for then fullstack application CLI"
    echo ""
    echo "Commands:"
    echo "  build           Build blue/green mode router docker image"
    echo "  start           Start blue/green mode router"
    echo "  stop            Stop blue/green mode router"
    echo "  reload-blue     Reload router config for the blue state"
    echo "  reload-green    Reload router config for the green state"
    echo "  sh              Run shell in router container"
    echo "  logs            Show logs output for the router service"
    echo "  cmd             Run command in the router service container"
    echo ""
    echo "Environments: "
    echo "  dev         Development environment"
    echo "  prod        Production environment"
    echo "  staging     Staging environment"
    echo "  test        Testing environment"
    echo ""
    echo "If omitted, will be used development environment."
    echo ""
    echo "Examples:"
    echo ""
    echo "  ./blue-green-router build"
    echo "  ./blue-green-router start dev"
    echo "  ./blue-green-router stop prod"
    echo "  ./blue-green-router logs dev"
    echo ""
esac