#!/bin/sh
WHITE='\033[1;37m'
RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
DARK_GRAY='\033[1;30m'
PURPLE='\033[0;35m'
NC='\033[0m'
RUNNING_ENVIRONMENT="development"
RUNNING_ENVIRONMENT_CMD="dev"
RUNNING_ENVIRONMENT_LABEL="${DARK_GRAY}${RUNNING_ENVIRONMENT}${NC}"
case "$2" in
  "dev")
        RUNNING_ENVIRONMENT="development"
        RUNNING_ENVIRONMENT_CMD="dev"
        RUNNING_ENVIRONMENT_LABEL="${DARK_GRAY}${RUNNING_ENVIRONMENT}${NC}"
      ;;
   "prod")
      RUNNING_ENVIRONMENT="production"
      RUNNING_ENVIRONMENT_CMD="prod"
      RUNNING_ENVIRONMENT_LABEL="${GREEN}${RUNNING_ENVIRONMENT}${NC}"
     ;;
   "staging")
      RUNNING_ENVIRONMENT="staging"
      RUNNING_ENVIRONMENT_CMD="staging"
      RUNNING_ENVIRONMENT_LABEL="${YELLOW}${RUNNING_ENVIRONMENT}${NC}"
     ;;
    "test")
      RUNNING_ENVIRONMENT="test"
      RUNNING_ENVIRONMENT_CMD="test"
      RUNNING_ENVIRONMENT_LABEL="${PURPLE}${RUNNING_ENVIRONMENT}${NC}"
     ;;
esac
ENV_VARS="$(cat environments/${RUNNING_ENVIRONMENT}/.env | xargs)"
export $(echo ${ENV_VARS} | xargs)
export "COMPOSE_PROJECT_NAME_PREFIX=${COMPOSE_PROJECT_NAME_PREFIX}"
export "LOCALHOST_PREFIX=$(if [[ $LOCALHOST_PREFIX ]]; then echo ${LOCALHOST_PREFIX}; else echo ''; fi)"
case "$1" in
  "build")
      CURRENT_BUILD="${WHITE}standalone${NC}"
      if [ "$CURRENT_STATE" == "blue" ]; then CURRENT_BUILD="${BLUE}blue${NC}";
      elif [ "$CURRENT_STATE" == "green" ]; then CURRENT_BUILD="${GREEN}green${NC}"; fi
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${CURRENT_BUILD}| ${YELLOW}building${NC} application ..."
      ./scripts 'eval docker-compose build --quiet' ${RUNNING_ENVIRONMENT_CMD}
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${CURRENT_BUILD}| build finished."
      ;;
  "start")
      if [[ $(docker network ls|grep "blue-green-${COMPOSE_PROJECT_NAME}") ]]; then echo "Network blue-green-${COMPOSE_PROJECT_NAME} exists."; else echo "Creating network blue-green-${COMPOSE_PROJECT_NAME} ..."; docker network create "blue-green-${COMPOSE_PROJECT_NAME}"; fi
      if [[ $(docker network ls|grep "standalone-${COMPOSE_PROJECT_NAME_PREFIX}${COMPOSE_PROJECT_NAME}") ]]; then echo "Network standalone-${COMPOSE_PROJECT_NAME_PREFIX}${COMPOSE_PROJECT_NAME} exists."; else echo "Creating network standalone-${COMPOSE_PROJECT_NAME_PREFIX}${COMPOSE_PROJECT_NAME} ..."; docker network create "standalone-${COMPOSE_PROJECT_NAME_PREFIX}${COMPOSE_PROJECT_NAME}"; fi
      CURRENT_BUILD="${WHITE}standalone${NC}"
      if [ "$CURRENT_STATE" == "blue" ]; then CURRENT_BUILD="${BLUE}blue${NC}";
      elif [ "$CURRENT_STATE" == "green" ]; then CURRENT_BUILD="${GREEN}green${NC}"; fi
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${CURRENT_BUILD}| ${LIGHT_GREEN}starting${NC} application ..."
      ./scripts 'eval docker-compose up -d' ${RUNNING_ENVIRONMENT_CMD}
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${CURRENT_BUILD}| application ${GREEN}started${NC}."
     ;;
  "stop")
      CURRENT_BUILD="${WHITE}standalone${NC}"
      if [ "$CURRENT_STATE" == "blue" ]; then CURRENT_BUILD="${BLUE}blue${NC}";
      elif [ "$CURRENT_STATE" == "green" ]; then CURRENT_BUILD="${GREEN}green${NC}"; fi
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${CURRENT_BUILD}| ${LIGHT_RED}stoping${NC} application ..."
      ./scripts 'eval docker-compose down' ${RUNNING_ENVIRONMENT_CMD}
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${CURRENT_BUILD}| application ${RED}stopped${NC}."
     ;;
  "deploy")
      DEPLOYMENT_VERSION_TAG=$3
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${DEPLOYMENT_VERSION_TAG}| ${LIGHT_GREEN}deploying${NC} application ..."
      cd "$(dirname "$0")"
      ./standalone stop $2
      git checkout tags/${DEPLOYMENT_VERSION_TAG}
      ./standalone build $2
      ./standalone start $2
      echo "|${COMPOSE_PROJECT_NAME}|${RUNNING_ENVIRONMENT_LABEL}|${CURRENT_BUILD}| application ${GREEN}deployed${NC}."
     ;;
  "sh")
      ./scripts 'eval docker exec -it ${COMPOSE_PROJECT_NAME}-nginx-router sh' ${RUNNING_ENVIRONMENT_CMD}
     ;;
  "logs")
    case "$2" in
      "router")
        ./scripts 'eval docker logs ${COMPOSE_PROJECT_NAME}-nginx-router' $3 $4 $5 $6 $7 $8 $9 
        ;;
      "frontend")
        ./scripts 'eval docker logs ${COMPOSE_PROJECT_NAME}-frontend' $3 $4 $5 $6 $7 $8 $9
        ;;
      "adminer")
        ./scripts 'eval docker logs ${COMPOSE_PROJECT_NAME}-adminer' $3 $4 $5 $6 $7 $8 $9
        ;;
      "mailhog")
        ./scripts 'eval docker logs ${COMPOSE_PROJECT_NAME}-mailhog' $3 $4 $5 $6 $7 $8 $9
        ;;
      "minio")
        ./scripts 'eval docker logs ${COMPOSE_PROJECT_NAME}-minio' $3 $4 $5 $6 $7 $8 $9
        ;;
      "minio-client")
        ./scripts 'eval docker logs ${COMPOSE_PROJECT_NAME}-minio-client' $3 $4 $5 $6 $7 $8 $9
        ;;
      *)
        echo ""
        echo "No options found for the logs command."
        echo ""
        echo "Please enter one of the following:"
        echo ""
        echo "    router          Logging for the nginx-router service"
        echo "    frontend        Logging for the frontend service"
        echo "    adminer         Logging for the adminer service"
        echo "    mailhog         Logging for the mailhog service"
        echo "    minio           Logging for the minio service"
        echo "    minio-client    Logging for the minio-client service"
        echo ""
        ;;
    esac
    ;;
  *)
    echo ""
    echo "usage: ./standalone COMMAND [OPTION] [ENVIRONMENT] [OPTIONS]"
    echo ""
    echo  "Standalone fullstack application CLI"
    echo ""
    echo "Commands:"
    echo "  build   Build docker images"
    echo "  start   Start application"
    echo "  stop    Stop application"
    echo "  deploy  Deploy application"
    echo "  sh      Run shell in nginx-router container"
    echo "  logs    Show logs output for the services"
    echo ""
    echo "Option: "
    echo "  for the logs command:"
    echo "    router          Logging for the nginx-router service"
    echo "    frontend        Logging for the frontend service"
    echo "    adminer         Logging for the adminer service"
    echo "    mailhog         Logging for the mailhog service"
    echo "    minio           Logging for the minio service"
    echo "    minio-client    Logging for the minio-client service"
    echo ""
    echo "Options: "
    echo "  for the logs command:"
    echo "    --follow        Follow log output"
    echo "    --tail string   Number of lines to show from the end of the logs (default "all")"
    echo ""
    echo "  for the deploy command:"
    echo "    [git tag]       Application version defined by git tag"
    echo ""
    echo "Environments: "
    echo "  dev         Development environment"
    echo "  prod        Production environment"
    echo "  staging     Staging environment"
    echo "  test        Testing environment"
    echo ""
    echo "If omitted, will be used development environment."
    echo ""
    echo "Examples:"
    echo ""
    echo "  ./standalone build"
    echo "  ./standalone start dev"
    echo "  ./standalone start prod"
    echo "  ./standalone logs dev router"
    echo "  ./standalone logs prod frontend --follow"
    echo "  ./standalone deploy prod 0.1.2"
    echo ""
esac